package project.datn.iam.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "orderdetail")
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class OrderDetail {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_orderdetail")
    private Long idOrderdetail;

    @ManyToOne
    @JoinColumn(name = "id_order",
            referencedColumnName = "id_order",
            foreignKey = @ForeignKey(name = "fk_orderdetail_productvariant"),
            nullable = false)
    private Order order;

    @ManyToOne
    @JoinColumn(
            name = "id_productvariant",
            referencedColumnName = "id_productvariant",
            foreignKey = @ForeignKey(name = "fk_orderdetail_productvariant"),
            nullable = false
    )
    private ProductVariant productVariant;

    @Column(name = "quantity", nullable = false)
    private Integer quantity;

    @Column(name = "originalprice", nullable = false)
    private Integer originalPrice;

    @Column(name = "price", nullable = false)
    private Integer price;

    @Column(name = "total", insertable = false, updatable = false)
    private Integer total; // generated by DB (quantity * price)
}


